"""empty message

Revision ID: 618aa3ad7ae0
Revises: 7250417a8691
Create Date: 2023-05-12 18:04:22.870324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618aa3ad7ae0'
down_revision = '7250417a8691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('coordinate_center_x', sa.Float(), nullable=False),
    sa.Column('coordinate_center_y', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('galaxy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'galaxy', ['galaxy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('galaxy_id')

    op.drop_table('galaxy')
    # ### end Alembic commands ###
