"""empty message

Revision ID: a17a280684a6
Revises: b86e3ce05eda
Create Date: 2023-05-15 13:06:20.964887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17a280684a6'
down_revision = 'b86e3ce05eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_column('favorite_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
